FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04

# Add environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Install system dependencies
RUN apt-get update && apt-get install -y \
  python3.11 python3.11-venv python3.11-dev \
  python3-pip \
  build-essential \
  cmake \
  git \
  curl \
  wget \
  unzip \
  libx11-6 \
  libgl1-mesa-glx \
  libglib2.0-0 \
  libvulkan1 \
  vulkan-tools \
  libjpeg-turbo8 \
  libpng-dev \
  libtinyexr-dev \
  libopenexr-dev \
  libpugixml-dev \
  libglfw3 \
  libglfw3-dev \
  libfmt-dev \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

# Update pip
RUN python3.11 -m pip install --upgrade pip

# Install PyTorch (CUDA 12.8 対応）
RUN pip install torch==2.7.0+cu128 --index-url https://download.pytorch.org/whl/cu128

# Install slangpy
RUN pip install slangpy

# set workspace
WORKDIR /workspace

# Change default python to python3.11
RUN ln -s /usr/bin/python3.11 /usr/bin/python

# Install uv
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates git
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"
